import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import MSWProvider from "@/src/providers/MSWProvider";
import ReactQueryProvider from "@/src/providers/RectQueryProvider";
import { cn } from "@/lib/utils";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/src/components/app-sidebar";
import { TooltipProvider } from "@/components/ui/tooltip";
import TopNavigation from "@/src/components/top-navigation";

const roboto = Roboto({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FleetPanda",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        roboto.variable
      )}
    >
      <body className="min-h-full flex flex-col">
        <MSWProvider>
          <ReactQueryProvider>
            <SidebarProvider>
              <TooltipProvider>
                <AppSidebar />
                <main className="w-full relative">
                  <TopNavigation />
                  <section className="p-4">{children}</section>
                </main>
              </TooltipProvider>
            </SidebarProvider>
          </ReactQueryProvider>
        </MSWProvider>
      </body>
    </html>
  );
}
